#!/usr/bin/env bash
builtin . "$GVM_ROOT/scripts/functions"

version=$1

if [ "$version" != "" ]; then
  # GREP_OPTIONS= keeps a colourised grep out of the name (issue #14)
  fuzzy_match=$($LS_PATH -1 "$GVM_ROOT/gos" | $SORT_PATH | GREP_OPTIONS= $GREP_PATH "$version" | $HEAD_PATH -n 1 | GREP_OPTIONS= $GREP_PATH "$version") ||
		display_fatal "Invalid version $version"

	foldername=$GVM_ROOT/gos/$fuzzy_match
else
	if [[ "$gvm_go_name" != "" ]]; then
		foldername=$GVM_ROOT/gos/$gvm_go_name
	else
		display_fatal "No version selected"
	fi
fi

if [[ -d $foldername ]]; then
	builtin cd "$foldername"
	find . > /tmp/manifest.test
	diff manifest /tmp/manifest.test
	if [[ "$?" == "0" ]]; then
		display_message "Clean $foldername"
	else
		display_message "*Dirty* $foldername"
	fi
else
	display_fatal "Invalid version"
fi
